package main

import (
	"assorted"
	_ "gobyexample"
	_ "goreceipes/concurrency"
	_ "goreceipes/fundamentals"
	_ "waytogo"
	_ "assorted/web_scraping"
	_ "goinpractise"
)

func main() {
	// gobyexample.HelloMain()
	// gbe.ArraysMain()
	// gbe.ConstantsMain()
	// gbe.ForMain()
	// gbe.IfelseMain()
	// gbe.SwitchMain()
	// gbe.ValuesMain()
	// gbe.VariablesMain()
	// assorted.ConstantsMain()
	// assorted.DoubleNumberMain()
	// assorted.FunctionsMain()
	// assorted.IntAndFloatMain()
	// assorted.SampleStructMain()
	// goinpractise.MutlipleReturnsMain()
	// goinpractise.ReadStatusMain()
	// goinpractise.ConcurrentPrintingMain()
	// goinpractise.UsingChannelMain()
	// goinpractise.FlagCliMain()
	// goinpractise.HelloServerMain()
	// assorted.ConvertStringMain()
	// assorted.MapDemoMain()
	// assorted.PassByValueMain()
	// assorted.PassByRefMain()
	// assorted.FuncAsObjMain()
	// assorted.AreaMain()
	// assorted.OOMthdInteritanceMain()
	// assorted.OOInterfaceMain()
	// assorted.InterfaceValueTypeMain()
	// assorted.GoRoutineMain()
	// assorted.NonBufferedChannels()
	// assorted.BufferedChannelsMain()
	// assorted.FiboMain()
	// assorted.ReadingDBMain()
	// concurrency.WaitGroupMain()
	// assorted.FetchUrlsMain()
	// assorted.CommunicationMain()
	// assorted.DeadlockMain()
	// concurrency.PassingTheBuckMain()
	// concurrency.PipelineMain()
	// concurrency.AsyncCommMain()
	// concurrency.MultiChannelCommMain()
	// fundamentals.MapIterationMain()
	// fundamentals.FileReadMain()
	// waytogo.ReadInputBasicMain()
	// waytogo.ReadWithBufIoMain()
	// waytogo.WordLetterCountMain()
	// web_scraping.ListPostsMain()
	// goinpractise.EchoMain()
	// goinpractise.AnonymousMain()
	// goinpractise.ZipFileMain()
	// goinpractise.ZipFileConcMain()
	// assorted.RedisPrimerMain()
	// assorted.SwearFilterMain()
	//assorted.EfficientStringConcatMain()
	//assorted.DoubleTheMoneyMain()
	assorted.StringLengthMain()
}
